steps:

# Workflow Runner

- name: 'gcr.io/cloud-builders/docker'
  id: build-sem-runner-image
  args: [ 'build', '-t', '${_IMAGE_REPO}/sem-${_DEV}-runner:latest', 
    '-f', 'src/dockerfiles/sem_runner.Dockerfile', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  id: push-sem-runner-image
  waitFor: ['build-sem-runner-image']
  args: ['push', '${_IMAGE_REPO}/sem-${_DEV}-runner:latest']





timeout: 900s

logsBucket:

substitutions:
    _IMAGE_REPO: prod/saf
    _DEV : prod
    # _CLUSTER_NAME: sdf
    # _COMPUTE_ZONE: us-central1-p
    

    # gcloud builds submit --timeout=900s --config ./cloudbuild.yaml . 
